### ISSUE TITLE
AL Loop Stop Safeguard

### ISSUE THREAD

**Issue by pol-sb** [pol-sb/MatDBForge#16]
## Overview
The current active learning (AL) loop stops when no disagreements are detected for a given seed and simulation temperature, time, etc. However, extended molecular dynamics (MD) simulations post-loop termination have occasionally revealed latent disagreements.

There exists a potential for disagreements to arise in scenarios where the AL loop has already terminated under the assumption that no further discrepancies exist for the given seed. This issue manifests especially during prolonged MD simulations, which could uncover latent discrepancies.

To address this, we propose implementing a safeguard involving a long-duration MD simulation (1 nanosecond) using the last trained model on a representative structure. This simulation will be checked for any disagreements and extrapolation errors that may not have been spotted during the standard AL loop run. The safeguard will be triggered after finishing an iteration of the AL-Loop and the condition for stopping the AL loop due to no disagreement is met.

## Considerations

- Structure Choice: Two ways of selecting the safeguard MD structure:
    - User-defined: The user provides an xyz file. This should be the preferred method, as the user will be able to select a structure representative of their target simulations.
    - Random: Select one at random from the database.

- Disagreement Checks: Specifically focus on identifying and logging any new disagreements or extrapolation errors that occur during the extended MD simulation.

- Integration into AL Loop: Seamlessly integrate this safeguard as an additional check that triggers post standard AL loop termination if the initial conditions are met.

- Add conditional flag to enable (always on by default)

## Planned procedure

- Add conditional flag to enable (always on by default)
- Use same disagreement check as in al loop (extrapolation + e/f or only e/f) 
- Include the check in `cls.check_al_loop_conditions`
- Or a single disagreement is enough to relaunch the loop

- Add settings entries (however, take some from regular MD settings)
```toml
[md]
[md.parameters]
...

[md.safeguard]
# Enable or disable the safeguard check
enable = true

# Target structure selection method.
# Either "random" or "user-defined"
structure_selection_method = "user-defined"

# path to user-defined structure
user_defined_struct_path = ""

# List of different temperatures (in K) to be used for the MD simulations.
# Ideally T should higher than the desired application.
temperature_list_K = 300.0

# Multiplier for the user-specified MD temperature to determine the upper
# bound of the temperature at the end of the simulation run.
max_temp_multiplier = 1.3

# Total number of timesteps for each MD simulation
# Length should be higher than the desired application.
num_steps = 1000

# Duration of each timestep (in ps).
timestep_duration_ps = 0.003

# Consider constant lattice when gathering trajectories
gather_traj_cnt_lattice = true

```
