### ISSUE TITLE
Allow use of MACE potentials for E & F predictions

### ISSUE THREAD

**Issue by pol-sb** [pol-sb/MatDBForge#17]
## Overview

Currently, our library supports electronic structure calculations exclusively through VASP. We propose to expand our computational methodology to include an alternative approach using a pretrained MACE machine learning potential. This addition will provide users with the flexibility to choose between traditional DFT calculations and a potentially faster, less resource-intensive machine learning approach.

## Planned Procedure

To accommodate this new feature, the user configuration file (TOML format) will be updated to allow users to select their preferred method for DFT calculations and to configure settings specific to the MACE potential. Below is the proposed configuration workflow:

```toml
# Active Learning Settings
[active_learning]

# Include new option to choose between calculation method
dft_method = "vasp"  # Options: "vasp", "mace"
...

# DFT Settings
[dft]

# Settings for VASP. Ignored if dft_method = "mace" 
[dft.vasp]
potential_family = "vasp-5.4-PBE-2023"

[dft.vasp.queue]
...

# MACE Settings as DFT calculator. Ignored if dft_method = "vasp" 
[dft.mace]
mace_potential_path = "/path/to/mace/potential/file"
device = "cuda"  # Options: "cpu", "cuda"
dtype = "float32"  # Options: "float32", "float64"
batch_size = 64
compute_stress = true  # Options: true, false
```
